### ISSUE TITLE
[Feature Request] Need to support UUID automatic generation 

### ISSUE THREAD

**Issue by WackyGem** [huyaro/CodeGenX#1]
Hello @huyaro 
I have been using your codegenx plugin with ORM library [Jimmer](https://babyfish-ct.github.io/jimmer/zh/docs/mapping/base/basic?_highlight=generationtype#%E6%95%B0%E6%8D%AE%E5%BA%93%E5%BA%8F%E5%88%97) recently , and found that UUID `UUIDIdGenerator`  is not  automatically generated.

I look forward to improving the plug-in generation function of UUID according to the following connection 
[数据库序列](https://babyfish-ct.github.io/jimmer/zh/docs/mapping/base/basic?_highlight=generationtype#%E6%95%B0%E6%8D%AE%E5%BA%93%E5%BA%8F%E5%88%97)
```
@Entity
interface Book {

    @Id
    @GeneratedValue(generatorType = UUIDIdGenerator::class)
    val id: UUID
}
```
Thank you very much for considering this!

**Comment by huyaro** [comment]
v0.1.9 is supported, you can update it after the jb-plugin market review.

**Comment by WackyGem** [comment]
That's really great !

feature https://github.com/huyaro/CodeGenX/commit/067b13b2c4bf3c5bba9d4477e6efe8425d0d78e9 testing as expected ,
issue done

 Thank you very much for your new feature update ！
