### ISSUE TITLE
父类在外置独立包 但是选择窗口选择不了外部jar的父类

### ISSUE THREAD

**Issue by qinkangdeid** [huyaro/CodeGenX#2]
IDEA版本：2023.3.2
插件版本：0.2.3

<img width="519" alt="image" src="https://github.com/huyaro/CodeGenX/assets/17582522/886f1511-bf2b-4eb5-97b3-12e34cddc967">

**Comment by huyaro** [comment]
[v0.2.4](https://github.com/huyaro/CodeGenX/tree/v0.2.4) 已调整为父类可输入，待 jb-market 更新后可用
不好意思，年底工作太忙，暂时没顾的上开源的事。
